//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyCalcClient.MyCalcSvcProxy {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="MyCalcSvcProxy.ISimpleCalculator")]
    public interface ISimpleCalculator {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISimpleCalculator/Add", ReplyAction="http://tempuri.org/ISimpleCalculator/AddResponse")]
        int Add(int num1, int num2);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ISimpleCalculatorChannel : MyCalcClient.MyCalcSvcProxy.ISimpleCalculator, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SimpleCalculatorClient : System.ServiceModel.ClientBase<MyCalcClient.MyCalcSvcProxy.ISimpleCalculator>, MyCalcClient.MyCalcSvcProxy.ISimpleCalculator {
        
        public SimpleCalculatorClient() {
        }
        
        public SimpleCalculatorClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SimpleCalculatorClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SimpleCalculatorClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SimpleCalculatorClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int Add(int num1, int num2) {
            return base.Channel.Add(num1, num2);
        }
    }
}
